### ISSUE TITLE
Backend error after install

### ISSUE THREAD

**Issue by ribsousa** [GrofGraf/octobercms-cookie-notice#1]
An error occured after installing this plugin (October build 428)
```php
Class GrofGraf\CookieNotice\Components\cookieNotice does not exist

```

**Comment by GrofGraf** [comment]
Hi, thank you for your comment. 

Can you elaborate a bit more. At what point an error occured? Is it possible you accidentally deleted the component folder of the plugin, because that was the only way I could reproduce your problem? 

Maybe compare folder structure in your project with the following: https://github.com/GrofGraf/octobercms-cookie-notice, it should be identical.

**Comment by ribsousa** [comment]
My folder structure in my project is identical.

After installing this plugin, when I visit:
```php
mysite/backend/cms
```
So show this error!

**Comment by GrofGraf** [comment]
I have no idea, why this happened. 
I tested it on a few projects and everywhere it works as espected. I would suggest deleting and reinstalling the plugin, maybe there was an error while downloading. 
If you still get an error you can paste your whole error log here and I will try to figure it out.

**Comment by GrofGraf** [comment]
Hi @ribsousa,
I bealive I fixed a problem with the latest build.
Feel free to download it and sorry for your inconvenience.
